### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by puncsky** [puncsky/extension-beancount-wallet#2]
* use ant design standards
* https://www.figma.com/file/j9KZeROzYXvdbFunW9sJFv/extension-beancount-wallet?node-id=0%3A1
* use styled from `onefx/lib/styletron` for styles

## v0.5

- [ ] wallet core @puncsky 
- [x] create account  https://github.com/puncsky/extension-beancount-wallet/issues/3 https://github.com/puncsky/extension-beancount-wallet/issues/4
- [x] lock wallet https://github.com/puncsky/extension-beancount-wallet/issues/5
- [x] add recoiljs for state management across components https://github.com/puncsky/extension-beancount-wallet/issues/7
- [x] import wallet by private key
- [x] secret store with chrome.storage sync
- [x] network selection
- [x] unlock wallet
- [x] multiple accounts UI
- [x] multiple accounts logic
- [x] balance and activity history
- [ ] assets table
- [x] send token: add recipient
- [ ] send token: multi assets
- [x] send token: send form
- [x] send token: send success
- [ ] security review
- [ ] release

## v1.0

- [ ] wallet core for dapp @puncsky 
- [x] dapp connect to website
- [ ] dapp multi provider switch
- [ ] dapp multi accounts switch
- [x] dapp patch antenna
- [x] dapp invoke contract
- [x] dapp envelop parsing and handling
- [x] dapp envelop siganature
- [x] dapp post action handling
